-- MySQL Script generated by MySQL Workbench
-- Wed May 12 01:43:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema admin_tas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema admin_tas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `admin_tas` DEFAULT CHARACTER SET utf8 ;
USE `admin_tas` ;

-- -----------------------------------------------------
-- Table `admin_tas`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin_tas`.`user` (
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_tas`.`topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin_tas`.`topic` (
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_tas`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin_tas`.`card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` MEDIUMTEXT NULL,
  `topic_name` VARCHAR(100) NULL,
  `answer` MEDIUMTEXT NULL,
  `option_1` MEDIUMTEXT NULL,
  `option_2` MEDIUMTEXT NULL,
  INDEX `topic_name_idx` (`topic_name` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `topic_name`
    FOREIGN KEY (`topic_name`)
    REFERENCES `admin_tas`.`topic` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_tas`.`mistake`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin_tas`.`mistake` (
  `username` VARCHAR(50) NOT NULL,
  `card_id` INT NULL,
  `chosen_answer` MEDIUMTEXT NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `question_idx` (`card_id` ASC),
  CONSTRAINT `mistake_to_user`
    FOREIGN KEY (`username`)
    REFERENCES `admin_tas`.`user` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `mistake_to_card`
    FOREIGN KEY (`card_id`)
    REFERENCES `admin_tas`.`card` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_tas`.`ticket_id`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin_tas`.`ticket_id` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_tas`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin_tas`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ticket_id` INT NULL,
  `card_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `ticket_id_idx` (`ticket_id` ASC),
  INDEX `question_idx` (`card_id` ASC),
  CONSTRAINT `ticket_to_card`
    FOREIGN KEY (`card_id`)
    REFERENCES `admin_tas`.`card` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ticket_to_id`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `admin_tas`.`ticket_id` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_tas`.`result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin_tas`.`result` (
  `ticket_id` INT NOT NULL,
  `username` VARCHAR(50) NULL,
  `points` INT NULL,
  `pass_time` TIME NULL,
  PRIMARY KEY (`ticket_id`),
  UNIQUE INDEX `ticket_id_UNIQUE` (`ticket_id` ASC),
  INDEX `username_idx` (`username` ASC),
  CONSTRAINT `result_to_user`
    FOREIGN KEY (`username`)
    REFERENCES `admin_tas`.`user` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `result_to_ticket`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `admin_tas`.`ticket_id` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
